# A redirect rule with all the supported properties
[[redirects]]
  from = "/"
  to = "/"
  force = true

[[redirects]]
  from = "/#home-blue"
  to = "/#home-blue"
  force = true

[[redirects]]
  from = "/#contact-us"
  to = "/#contact-us"
  force = true

[[redirects]]
  from = "/about"
  to = "/about"
  force = true

[[redirects]]
  from = "/community"
  to = "/community"
  force = true

[[redirects]]
  from = "/community#Events"
  to = "/community#Events"
  force = true

[[redirects]]
  from = "/community#Resources"
  to = "/community#Resources"
  force = true

[[redirects]]
  from = "/community#contact-us"
  to = "/community#contact-us"
  force = true

[[redirects]]
  from = "/work"
  to = "/work"
  force = true

[[redirects]]
  from = "/work#Process"
  to = "/work#Process"
  force = true

[[redirects]]
  from = "/work#Services"
  to = "/work#Services"
  force = true

[[redirects]]
  from = "/work#contact-us"
  to = "/work#contact-us"
  force = true
